# Generated by Django 4.0.1 on 2022-02-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_salesorder_delete_slesorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOfManufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
    ]
